### ISSUE TITLE
終了時にエラーが毎回でます

### ISSUE THREAD

**Issue by 8yazaki** [diginatu/nagome-electron#2]
バージョン：1.0.0
Mac版

バツボタンからではなく、cmd+qで終了する際に以下の様なエラーメッセージが毎回出ていまします。
コメビュとしての動作には問題はありません。

<img width="421" alt="2018-06-23 17 45 02" src="https://user-images.githubusercontent.com/8017778/41807701-9f541d3a-770d-11e8-9176-f1a19cc702ca.png">

**Comment by diginatu** [comment]
報告ありがとうございます
原因がわかったので修正します
