### ISSUE TITLE
How to make it say comments written?

### ISSUE THREAD

**Issue by dora-gt** [diginatu/nagome-electron#5]
Hi, thank you for developing such a nice app.

I'm curious about how to make it say comments written.
Is there a nice document on this?

**Comment by diginatu** [comment]
Are you finding a way to read aloud comments?
If so, Nagome's plugin mechanism can help.
I'm using this plugin.  But it needs AWS Polly token.
https://github.com/bamchoh/nagome-polly

You can easily create plugins.  And examples are found here.
https://github.com/topics/nagome-plugin
